language: julia

os:
  - linux

julia:
  - 1.6
  - nightly

notifications:
  email: false

jobs:
  fast_finish: true

jobs:
  include:
    - julia: 1.6
      os: osx
  fast_finish: true
  allow_failures:
    - os: osx
    - julia: nightly

addons:
  apt:
    packages:
      - hdf5-tools

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("RoMEPlotting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
