language: julia

os:
  - linux

julia:
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false

jobs:
  fast_finish: true

jobs:
  include:
    - julia: 1.4
      os: osx
  fast_finish: true
  allow_failures:
    - os: osx
    - julia: nightly

addons:
  apt:
    packages:
      - hdf5-tools

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --check-bounds=yes -e 'using Pkg; Pkg.develop("Compose"); Pkg.clone(pwd()); Pkg.build("RoMEPlotting"); Pkg.test("RoMEPlotting"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("RoMEPlotting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
